//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesPlugin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesPlugin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourcesPlugin", typeof(ResourcesPlugin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Group.
        /// </summary>
        public static string AccountGroup {
            get {
                return ResourceManager.GetString("AccountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Payable.
        /// </summary>
        public static string AccountPayable {
            get {
                return ResourceManager.GetString("AccountPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Receivable.
        /// </summary>
        public static string AccountReceivable {
            get {
                return ResourceManager.GetString("AccountReceivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Sheet.
        /// </summary>
        public static string BalanceSheet {
            get {
                return ResourceManager.GetString("BalanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budgeting.
        /// </summary>
        public static string Budgeting {
            get {
                return ResourceManager.GetString("Budgeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Of Account.
        /// </summary>
        public static string ChartOfAccount {
            get {
                return ResourceManager.GetString("ChartOfAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Note.
        /// </summary>
        public static string CreditNote {
            get {
                return ResourceManager.GetString("CreditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Note.
        /// </summary>
        public static string DebitNote {
            get {
                return ResourceManager.GetString("DebitNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Asset.
        /// </summary>
        public static string FixedAsset {
            get {
                return ResourceManager.GetString("FixedAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Ledger.
        /// </summary>
        public static string GeneralLedger {
            get {
                return ResourceManager.GetString("GeneralLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resource.
        /// </summary>
        public static string HumanResource {
            get {
                return ResourceManager.GetString("HumanResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.
        /// </summary>
        public static string Payroll {
            get {
                return ResourceManager.GetString("Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit and Loss.
        /// </summary>
        public static string ProfitAndLoss {
            get {
                return ResourceManager.GetString("ProfitAndLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing.
        /// </summary>
        public static string Purchasing {
            get {
                return ResourceManager.GetString("Purchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Balance.
        /// </summary>
        public static string TrialBalance {
            get {
                return ResourceManager.GetString("TrialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Inbox.
        /// </summary>
        public static string WorkflowInbox {
            get {
                return ResourceManager.GetString("WorkflowInbox", resourceCulture);
            }
        }
    }
}
