//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesGL
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesGL()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourcesGL", typeof(ResourcesGL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account Group Setup.
        /// </summary>
        public static string AccountGroupSetup
        {
            get
            {
                return ResourceManager.GetString("AccountGroupSetup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account Payable.
        /// </summary>
        public static string AccountPayable
        {
            get
            {
                return ResourceManager.GetString("AccountPayable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account Receivable.
        /// </summary>
        public static string AccountReceivable
        {
            get
            {
                return ResourceManager.GetString("AccountReceivable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activity Group Setup.
        /// </summary>
        public static string ActivityGroupSetup
        {
            get
            {
                return ResourceManager.GetString("ActivityGroupSetup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activity Setup.
        /// </summary>
        public static string ActivitySetup
        {
            get
            {
                return ResourceManager.GetString("ActivitySetup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activity Sub Setup.
        /// </summary>
        public static string ActivitySubSetup
        {
            get
            {
                return ResourceManager.GetString("ActivitySubSetup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin
        {
            get
            {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account Setup.
        /// </summary>
        public static string ChartOfAccountSetup
        {
            get
            {
                return ResourceManager.GetString("ChartOfAccountSetup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer Setup.
        /// </summary>
        public static string Customer
        {
            get
            {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General Ledger.
        /// </summary>
        public static string GeneralLedger
        {
            get
            {
                return ResourceManager.GetString("GeneralLedger", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice
        {
            get
            {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string Journal
        {
            get
            {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment
        {
            get
            {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vendor Setup.
        /// </summary>
        public static string Vendor
        {
            get
            {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
    }
}
