//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccountingExt.
        /// </summary>
        public static string AccountingExt
        {
            get
            {
                return ResourceManager.GetString("AccountingExt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin
        {
            get
            {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to App Setup.
        /// </summary>
        public static string AppSetup
        {
            get
            {
                return ResourceManager.GetString("AppSetup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Budget2DB.
        /// </summary>
        public static string Budget2DB
        {
            get
            {
                return ResourceManager.GetString("Budget2DB", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string Code
        {
            get
            {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact
        {
            get
            {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field1.
        /// </summary>
        public static string Field1
        {
            get
            {
                return ResourceManager.GetString("Field1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home
        {
            get
            {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logon.
        /// </summary>
        public static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        public static string Logoff
        {
            get
            {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register
        {
            get
            {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role Setup.
        /// </summary>
        public static string RoleSetup
        {
            get
            {
                return ResourceManager.GetString("RoleSetup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Setup Plugin.
        /// </summary>
        public static string SetupPlugin
        {
            get
            {
                return ResourceManager.GetString("SetupPlugin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System
        {
            get
            {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User Setup.
        /// </summary>
        public static string UserSetup
        {
            get
            {
                return ResourceManager.GetString("UserSetup", resourceCulture);
            }
        }
    }
}
